import { useEffect, useRef } from 'react'
import { motion } from 'framer-motion'
import { worldCupPlayerById as playerById } from '../../services/worldcup/worldCupRepository'
import type { SimulationEvent } from '../../entities/simulation/types'
import type { SimulationInput } from '../../entities/tactic/types'

type Point={x:number;y:number}
type Route={points:Point[];receivers:(number|null)[];userAttacking:boolean}

const opponentShape:Point[]=[{x:50,y:8},{x:18,y:24},{x:39,y:20},{x:61,y:20},{x:82,y:24},{x:28,y:43},{x:50,y:48},{x:72,y:43},{x:18,y:68},{x:50,y:76},{x:82,y:68}]
const clamp=(value:number)=>Math.max(3,Math.min(97,value))
const distance=(a:Point,b:Point)=>Math.hypot(a.x-b.x,a.y-b.y)

function nearestPlayer(players:Point[],target:Point,used:Set<number>){let best=-1,bestDistance=Infinity;players.forEach((player,index)=>{const score=distance(player,target)+(used.has(index)?28:0);if(score<bestDistance){best=index;bestDistance=score}});if(best>=0)used.add(best);return best}
function finishPoint(event:SimulationEvent,userAttacking:boolean):Point{const attackY=(value:number)=>userAttacking?value:100-value;if(event.type==='goal')return{x:50,y:attackY(2)};if(['shot','big_chance','save'].includes(event.type))return{x:50,y:attackY(8)};return{x:50,y:attackY(32)}}

function buildRoute(event:SimulationEvent|undefined,input:SimulationInput,start:Point):Route{const userAttacking=event?.teamId===input.teamId;if(!event)return{points:[start],receivers:[null],userAttacking};const players=userAttacking?input.players.map(player=>({x:player.x,y:player.y})):opponentShape;const attackY=(value:number)=>userAttacking?value:100-value;const laneX=input.instructions.attackDirection==='left'?22:input.instructions.attackDirection==='right'?78:event.minute%2?24:76;const shooting=['goal','shot','big_chance','save','box_entry'].includes(event.type);const targets:Point[]=shooting?[{x:50,y:attackY(68)},{x:laneX,y:attackY(45)},{x:laneX,y:attackY(22)}]:event.type==='wing_attack'||event.type==='set_piece'?[{x:50,y:attackY(66)},{x:laneX,y:attackY(45)},{x:laneX,y:attackY(31)}]:event.type==='central_attack'?[{x:50,y:attackY(66)},{x:50,y:attackY(48)},{x:50,y:attackY(33)}]:event.type==='counter_attack'?[{x:50,y:attackY(62)},{x:laneX,y:attackY(40)},{x:50,y:attackY(27)}]:[{x:50,y:attackY(70)},{x:laneX,y:attackY(52)}];const used=new Set<number>(),receivers:(number|null)[]=[null],points=[start];targets.forEach(target=>{const receiver=nearestPlayer(players,target,used);points.push(players[receiver]??target);receivers.push(receiver)});if(shooting){points.push(finishPoint(event,userAttacking));receivers.push(null)}return{points,receivers,userAttacking}}

function playerMotionPath(base:Point,index:number,route:Route,attacking:boolean,start:Point,event:SimulationEvent|undefined):Point[]{const attackDirection=attacking?(route.userAttacking?-1:1):0;return route.points.map((ball,step)=>{if(step===0)return start;if(attacking&&route.receivers[step]===index)return ball;const progress=step/Math.max(1,route.points.length-1),range=distance(base,ball),near=Math.max(0,1-range/85);const support=attacking?.08+near*.16:.06+near*.22;const weave=Math.sin((event?.minute??0)*.31+index*1.7+step*.9)*(attacking?5.5:4);const forward=attacking&&index!==0?attackDirection*progress*(4+(index%3)*1.4):0;return{x:clamp(base.x+(ball.x-base.x)*support+weave),y:clamp(base.y+(ball.y-base.y)*support+forward)}})}

export function MatchPitch({input,event}:{input:SimulationInput;event?:SimulationEvent}){const previousBall=useRef<Point>({x:50,y:50}),previousPlayers=useRef(new Map<string,Point>()),route=buildRoute(event,input,previousBall.current),end=route.points[route.points.length-1];const userBases=input.players.map(player=>({x:player.x,y:player.y})),userPaths=userBases.map((base,index)=>playerMotionPath(base,index,route,route.userAttacking,previousPlayers.current.get(`user-${input.players[index].playerId}`)??base,event)),opponentPaths=opponentShape.map((base,index)=>playerMotionPath(base,index,route,!route.userAttacking,previousPlayers.current.get(`opponent-${index}`)??base,event));const times=route.points.map((_,index)=>index/Math.max(1,route.points.length-1)),transition={duration:.69,ease:[.35,0,.25,1] as [number,number,number,number],times}
  useEffect(()=>{previousBall.current=end;userPaths.forEach((path,index)=>previousPlayers.current.set(`user-${input.players[index].playerId}`,path[path.length-1]));opponentPaths.forEach((path,index)=>previousPlayers.current.set(`opponent-${index}`,path[path.length-1]))},[event?.id])
  return <div className="relative aspect-[92/68] overflow-hidden rounded-2xl border-2 border-white/40 bg-emerald-800 shadow-inner">
    <div className="absolute inset-0 bg-[repeating-linear-gradient(90deg,rgba(255,255,255,.035)_0,rgba(255,255,255,.035)_12.5%,transparent_12.5%,transparent_25%)]"/>
    <div className="absolute inset-y-0 left-1/2 border-l border-white/45"/><div className="absolute left-1/2 top-1/2 size-24 -translate-x-1/2 -translate-y-1/2 rounded-full border border-white/45"/>
    <div className="absolute -left-px top-[27%] h-[46%] w-[15%] border border-l-0 border-white/45"/><div className="absolute -right-px top-[27%] h-[46%] w-[15%] border border-r-0 border-white/45"/>
    <div className="absolute -left-px top-[39%] h-[22%] w-[5%] border border-l-0 border-white/45"/><div className="absolute -right-px top-[39%] h-[22%] w-[5%] border border-r-0 border-white/45"/>
    {input.players.map((placement,index)=>{const player=playerById.get(placement.playerId),path=userPaths[index];return <motion.div key={placement.playerId} data-match-player="user" className="absolute z-10 grid size-5 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border border-white bg-green-400 text-[8px] font-black text-slate-950 shadow-lg sm:size-6" animate={{left:path.map(point=>`${point.y}%`),top:path.map(point=>`${point.x}%`)}} initial={false} transition={transition} title={player?.name}>{player?.shirtNumber??index+1}</motion.div>})}
    {opponentShape.map((_,index)=>{const path=opponentPaths[index];return <motion.div key={index} data-match-player="opponent" className="absolute z-10 grid size-5 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border border-white/80 bg-red-400 text-[8px] font-black text-slate-950 shadow-lg sm:size-6" animate={{left:path.map(point=>`${point.y}%`),top:path.map(point=>`${point.x}%`)}} initial={false} transition={transition}>{index+1}</motion.div>})}
    <motion.div data-match-ball className="absolute z-20 size-3 -translate-x-1/2 -translate-y-1/2 rounded-full border border-zinc-400 bg-white shadow-[0_2px_10px_rgba(0,0,0,.85)]" animate={{left:route.points.map(point=>`${point.y}%`),top:route.points.map(point=>`${point.x}%`),scale:event?.type==='goal'?route.points.map((_,index)=>index===route.points.length-1?1.7:index===route.points.length-2?1.15:1):1}} initial={false} transition={transition}/>
    {event?.type==='goal'&&<motion.div key={event.id} className="pointer-events-none absolute inset-0 z-30 grid place-items-center bg-green-300/25 text-4xl font-black italic text-white" initial={{opacity:0,scale:.8}} animate={{opacity:[0,1,1,0],scale:[.8,1.08,1.03,1]}} transition={{duration:1.35,times:[0,.22,.72,1]}}>GOAL!</motion.div>}
    <div className="absolute bottom-2 left-2 z-30 flex gap-3 rounded-full bg-slate-950/75 px-3 py-1 text-[9px] font-bold"><span className="text-green-300">● 우리 팀</span><span className="text-red-300">● 상대 팀</span></div>
  </div>
}
