import { useEffect, useMemo, useState } from 'react'
import { useAppStore } from '../../app/appStore'
import { getWorldCupMission as getMission } from '../../services/worldcup/worldCupRepository'
import { runSimulation } from '../../engine/runMonteCarloSimulation'
import { ActionButton } from '../../shared/components/ActionButton'
import { CommentaryFeed } from './CommentaryFeed'
import { MatchAnalysisPanel } from './MatchAnalysisPanel'
import { MatchClock } from './MatchClock'
import { MatchPitch } from './MatchPitch'

const playbackDelay=(type:string)=>type==='goal'?1800:700
export function SimulationPage(){const input=useAppStore(s=>s.simulationInput),saved=useAppStore(s=>s.simulationResult),save=useAppStore(s=>s.setSimulationResult),next=useAppStore(s=>s.goToNextStep);const result=useMemo(()=>input?(saved?.missionId===input.missionId?saved:runSimulation(input,300)):null,[input,saved]);const [shown,setShown]=useState(1),[paused,setPaused]=useState(false),[speed,setSpeed]=useState(1)
  useEffect(()=>{if(result&&!saved)save(result)},[result,saved,save]);useEffect(()=>{setShown(1);setPaused(false)},[result]);useEffect(()=>{if(!result||paused||shown>=result.timeline.length)return;const timer=window.setTimeout(()=>setShown(value=>Math.min(result.timeline.length,value+1)),playbackDelay(result.timeline[Math.max(0,shown-1)].type)/speed);return()=>window.clearTimeout(timer)},[result,paused,shown,speed])
  if(!input||!result)return <section className="mx-auto max-w-3xl px-5 py-20 text-center"><h1 className="text-2xl font-black">전술 입력이 없습니다</h1><p className="mt-3 text-zinc-400">미션을 다시 선택해 전술을 저장해주세요.</p></section>
  const mission=getMission(input.missionId),events=result.timeline.slice(0,shown),current=events[events.length-1],complete=shown>=result.timeline.length
  return <section className="mx-auto max-w-7xl px-5 py-12 sm:px-8"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-green-400">Live IF simulation</p><h1 className="mt-2 text-2xl font-black">{mission.title}</h1><p className="mt-1 text-xs text-zinc-500">{result.followsActualBaseline?'전술 변화가 작아 실제 경기 흐름을 재생합니다.':`Monte Carlo ${result.monteCarloRuns}회 · 최빈 스코어 대표 경기`}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${complete?'bg-zinc-800 text-zinc-300':'bg-red-400/10 text-red-300'}`}>{complete?'● FULL TIME':paused?'Ⅱ PAUSED':'● LIVE'}</span></div><div className="mt-8 overflow-hidden rounded-3xl border border-white/10 bg-zinc-900/70"><div className="border-b border-white/10 py-5"><MatchClock minute={current?.minute??mission.context.minute} score={current?.score??mission.context.score}/><div className="mt-4 flex justify-center gap-2"><button type="button" disabled={complete} onClick={()=>setPaused(value=>!value)} className="rounded-lg border border-white/10 bg-slate-950 px-3 py-1.5 text-xs font-bold text-zinc-300 disabled:opacity-40">{paused?'▶ 재개':'Ⅱ 일시정지'}</button><button type="button" disabled={complete} onClick={()=>setSpeed(value=>value===1?2:value===2?4:1)} className="rounded-lg border border-white/10 bg-slate-950 px-3 py-1.5 font-mono text-xs font-bold text-zinc-300 disabled:opacity-40">{speed}× 속도</button></div></div><div className="grid gap-0 lg:grid-cols-[minmax(0,1.45fr)_minmax(320px,.75fr)]"><div className="border-b border-white/10 p-4 sm:p-6 lg:border-b-0 lg:border-r"><MatchPitch input={input} event={current}/><MatchAnalysisPanel events={events} userTeamId={input.teamId} score={current?.score??mission.context.score}/></div><div className="max-h-[620px] overflow-y-auto p-4 sm:p-6"><CommentaryFeed events={events} userTeamId={input.teamId}/></div></div></div><div className="mt-5 flex items-center justify-between gap-4"><p className="text-xs text-zinc-500">주요 장면 중심 중계 · 같은 전술 입력은 같은 결과와 확률을 생성합니다.</p><ActionButton onClick={next}>{complete?'결과 확인 →':'결과 바로 보기 →'}</ActionButton></div></section>}
