import { beforeEach, describe, expect, it } from 'vitest'
import { defaultInstructions } from '../../data/tactics'
import { calculateTacticalEffects } from '../../engine/calculateTacticalEffects'
import { calculateTeamMetrics } from '../../engine/calculateTeamMetrics'
import { getLineupForMission, getWorldCupMission as getMission, worldCupMissions } from '../../services/worldcup/worldCupRepository'
import { useTacticEditorStore } from './tacticEditorStore'

describe('tactic editor',()=>{
  beforeEach(()=>useTacticEditorStore.setState({missionId:null,substitutions:[]}))
  it('starts a penalty-order mission with a full lineup context',()=>{const mission=worldCupMissions.find(item=>item.type==='penalty_order')??worldCupMissions[0];useTacticEditorStore.getState().initialize(mission.id);expect(useTacticEditorStore.getState().players).toHaveLength(11)})
  it('substitutes a bench player and records the change',()=>{const mission=worldCupMissions.find(item=>item.type==='trailing_draw')??worldCupMissions[0];const store=useTacticEditorStore.getState();store.initialize(mission.id);const state=useTacticEditorStore.getState(),outId=state.players[0].playerId,inId=state.benchPlayerIds[0];state.substitute(outId,inId);expect(useTacticEditorStore.getState().players.some(p=>p.playerId===inId)).toBe(true);expect(useTacticEditorStore.getState().substitutions).toEqual([{outPlayerId:outId,inPlayerId:inId}])})
  it('keeps freely moved players inside the visible pitch',()=>{const mission=worldCupMissions[0];useTacticEditorStore.getState().initialize(mission.id);const playerId=useTacticEditorStore.getState().players[0].playerId;useTacticEditorStore.getState().movePlayer(playerId,-20,140);expect(useTacticEditorStore.getState().players.find(player=>player.playerId===playerId)).toMatchObject({x:4,y:96})})
  it('serializes a complete SimulationInput',()=>{const mission=worldCupMissions.find(item=>item.type==='late_winner')??worldCupMissions[0];useTacticEditorStore.getState().initialize(mission.id);const input=useTacticEditorStore.getState().toSimulationInput();expect(input).toMatchObject({missionId:mission.id,formationId:getMission(mission.id).recommendedFormationId});expect(input?.players).toHaveLength(11)})
  it('shows the same core metrics used by the simulation engine',()=>{const mission=worldCupMissions.find(item=>item.type==='late_winner')??worldCupMissions[0];useTacticEditorStore.getState().initialize(mission.id);const input=useTacticEditorStore.getState().toSimulationInput();expect(input).toBeTruthy();const metrics=calculateTeamMetrics(input!);expect(input?.expectedEffects).toMatchObject({attack:Math.round(metrics.attackPower),defensiveStability:Math.round(metrics.defenseStability),midfieldControl:Math.round(metrics.midfieldControl),chanceCreation:Math.round(metrics.chanceCreation),counterRisk:Math.round(metrics.counterRisk),setPieceThreat:Math.round(metrics.setPieceThreat)})})
  it('places actual lineup players by position group',()=>{const mission=worldCupMissions.find(item=>item.type==='group_stage_escape')??worldCupMissions[0];useTacticEditorStore.getState().initialize(mission.id);const state=useTacticEditorStore.getState();const keeper=state.players.find(item=>state.positionOverrides[item.playerId]==='GK');const forward=state.players.find(item=>state.positionOverrides[item.playerId]==='ST'||state.positionOverrides[item.playerId]==='LW'||state.positionOverrides[item.playerId]==='RW');expect(keeper?.y).toBeGreaterThan(80);expect(forward?.y).toBeLessThan(40)})
  it('loads each selected team lineup for a tied fixture choice',()=>{const pair=worldCupMissions.filter((mission,index,items)=>items.some((other,otherIndex)=>otherIndex!==index&&other.relatedFixtureId===mission.relatedFixtureId&&other.type===mission.type&&other.context.minute===mission.context.minute));expect(pair.length).toBeGreaterThanOrEqual(2);const [first]=pair;const second=pair.find(mission=>mission.relatedFixtureId===first.relatedFixtureId&&mission.type===first.type&&mission.context.userTeamId!==first.context.userTeamId);expect(second).toBeTruthy();useTacticEditorStore.getState().initialize(first.id);const firstPlayers=useTacticEditorStore.getState().players.map(player=>player.playerId);expect(firstPlayers).toEqual(expect.arrayContaining(getLineupForMission(first.id)?.startXI.map(player=>player.id)??[]));useTacticEditorStore.getState().initialize(second?.id??'');const secondPlayers=useTacticEditorStore.getState().players.map(player=>player.playerId);expect(secondPlayers).toEqual(expect.arrayContaining(getLineupForMission(second?.id??null)?.startXI.map(player=>player.id)??[]));expect(new Set(firstPlayers)).not.toEqual(new Set(secondPlayers))})
  it('raises attack and counter risk for aggressive fast tactics',()=>{const mission=worldCupMissions.find(item=>item.type==='trailing_draw')??worldCupMissions[0];useTacticEditorStore.getState().initialize(mission.id);const players=useTacticEditorStore.getState().players;const balanced=calculateTacticalEffects(players,{...defaultInstructions,defensiveLine:'medium',pressingIntensity:'medium',tempo:'balanced',attackDirection:'balanced',riskLevel:'balanced'});const aggressive=calculateTacticalEffects(players,{...defaultInstructions,defensiveLine:'high',pressingIntensity:'high',tempo:'fast',attackDirection:'center',riskLevel:'aggressive'});expect(aggressive.attack).toBeGreaterThan(balanced.attack);expect(aggressive.counterRisk).toBeGreaterThan(balanced.counterRisk)})
})
