import { worldCupPlayerById as playerById, getWorldCupTeam as getTeam } from '../services/worldcup/worldCupRepository'
import type { TeamMetrics } from '../entities/simulation/types'
import type { PlayerPlacement, SimulationInput, TacticalInstructions } from '../entities/tactic/types'
import { calculatePlayerInfluence } from './calculatePlayerInfluence'

const clamp=(n:number)=>Math.max(1,Math.min(99,n));const average=(values:number[])=>values.reduce((a,b)=>a+b,0)/Math.max(1,values.length)
const modifiers=(i:TacticalInstructions)=>({press:i.pressingIntensity==='high'?10:i.pressingIntensity==='low'?-7:0,line:i.defensiveLine==='high'?8:i.defensiveLine==='low'?-7:0,tempo:i.tempo==='fast'?8:i.tempo==='slow'?-6:0,risk:i.riskLevel==='aggressive'?11:i.riskLevel==='safe'?-9:0,width:i.width==='wide'?6:i.width==='narrow'?-3:0,direct:i.buildUpStyle==='direct'?7:i.buildUpStyle==='possession'?-3:0,possession:i.buildUpStyle==='possession'?7:0,cross:i.chanceCreation==='crosses'?7:0,through:i.chanceCreation==='through_balls'?7:0,zonal:i.defensiveApproach==='zonal'?5:0,man:i.defensiveApproach==='man_marking'?5:0})
export function calculateLineupMetrics(players:PlayerPlacement[],instructions:TacticalInstructions,staminaFactor=1):TeamMetrics{const influences=players.map(p=>{const player=playerById.get(p.playerId);return player?calculatePlayerInfluence(player,p.role,staminaFactor):null}).filter((x):x is NonNullable<typeof x>=>Boolean(x));const m=modifiers(instructions);return {attackPower:clamp(average(influences.map(x=>x.attack))+m.tempo*.45+m.risk*.7+m.direct*.35+m.through*.35),defenseStability:clamp(average(influences.map(x=>x.defense))-m.line*.45-m.risk*.45+m.zonal*.55+m.man*.2),midfieldControl:clamp(average(influences.map(x=>x.midfield))+m.press*.25+m.possession*.55),chanceCreation:clamp(average(influences.map(x=>x.creation))+m.tempo*.65+m.risk*.45+m.width*.4+m.cross*.45+m.through*.5+m.possession*.25),counterRisk:clamp(30+m.line*1.8+m.press*.8+m.risk*1.25+m.direct*.45+m.man*.55-m.zonal*.35),setPieceThreat:clamp(average(influences.map(x=>x.setPiece))+m.cross*.65+m.width*.25),staminaLevel:clamp(average(influences.map(x=>x.stamina))-Math.max(0,m.man)*.35),pressingPower:clamp(average(influences.map(x=>x.pressing))+m.press+m.man*.3),transitionThreat:clamp(average(influences.map(x=>x.transition))+m.tempo*.35+m.risk*.45+m.direct*.55+m.through*.25)}}
export function calculateTeamMetrics(input:SimulationInput,staminaFactor=1):TeamMetrics{return calculateLineupMetrics(input.players,input.instructions,staminaFactor)}
export function calculateOpponentMetrics(input:SimulationInput,staminaFactor=1):TeamMetrics{const team=getTeam(input.opponentTeamId),players=team.startingPlayerIds.map(id=>playerById.get(id)).filter((x):x is NonNullable<typeof x>=>Boolean(x)),avg=(key:keyof typeof players[number]['attributes'])=>average(players.map(p=>p.attributes[key]))*staminaFactor;return {attackPower:clamp(avg('finishing')*.5+avg('offBall')*.3+avg('passing')*.2),defenseStability:clamp(avg('defense')*.7+avg('stamina')*.3),midfieldControl:clamp(avg('passing')*.6+avg('pressing')*.4),chanceCreation:clamp(avg('passing')*.45+avg('dribbling')*.3+avg('crossing')*.25),counterRisk:38,setPieceThreat:clamp(avg('heightPower')*.65+avg('crossing')*.35),staminaLevel:clamp(avg('stamina')),pressingPower:clamp(avg('pressing')),transitionThreat:clamp(avg('pace')*.55+avg('offBall')*.45)}}
