import { getWorldCupMission as getMission } from '../services/worldcup/worldCupRepository'
import type { MatchPeriod, Mission } from '../entities/mission/types'
import type { SimulationEvent, SingleSimulationResult } from '../entities/simulation/types'
import type { SimulationInput } from '../entities/tactic/types'
import { calculateOpponentMetrics, calculateTeamMetrics } from './calculateTeamMetrics'
import { evaluateMissionResult } from './evaluateMissionResult'
import { generateSimulationEvent } from './generateSimulationEvent'
import { createSeededRandom } from './random'

const periodFor=(minute:number):MatchPeriod=>minute<=45?'FIRST_HALF':minute<=90?'SECOND_HALF':minute<=105?'EXTRA_TIME_FIRST_HALF':'EXTRA_TIME_SECOND_HALF'
export function allowsExtraTime(mission:Mission){const stage=mission.context.stage.toLowerCase();return !stage.includes('group')&&!stage.includes('조별리그')}
export function shouldEnterExtraTime(mission:Mission,minute:number,scheduledEnd:number,score:{home:number;away:number}){return minute===90&&scheduledEnd===90&&allowsExtraTime(mission)&&score.home===score.away}
const effectKeys=(['attack','defensiveStability','midfieldControl','chanceCreation','counterRisk','setPieceThreat'] as const)
export function tacticalChangeScore(input:SimulationInput){const differences=effectKeys.map(key=>Math.abs(input.expectedEffects[key]-input.baselineEffects[key]));const average=differences.reduce((sum,value)=>sum+value,0)/differences.length;return average+Math.max(...differences)*.5+input.substitutions.length*4}
function actualType(type:string):SimulationEvent['type']{return type==='goal'?'goal':type==='shot'?'shot':type==='save'?'save':type==='red_card'?'card':type==='full_time'?'defensive_block':type==='substitution'?'build_up':'progressive_pass'}
function actualFlowResult(input:SimulationInput,seed:number):SingleSimulationResult{const mission=getMission(input.missionId);const events=mission.actualTimeline.filter(event=>event.minute>mission.context.minute).map((event,index)=>({id:`actual-${event.id}-${index}`,minute:event.minute,period:event.period,teamId:event.teamId,type:actualType(event.type),text:event.summary,score:{home:event.homeScore,away:event.awayScore},momentumDelta:event.teamId===input.teamId?3:-3,probability:1,isKeyEvent:event.type==='goal'||event.type==='red_card'||event.type==='full_time'}));const timeline=events.length?events:[{id:'actual-baseline-end',minute:mission.objective.targetMinute,period:periodFor(mission.objective.targetMinute),teamId:input.teamId,type:'defensive_block',text:'전술 변화가 크지 않아 실제 경기 흐름이 이어집니다.',score:{...mission.context.score},momentumDelta:0,probability:1,isKeyEvent:true} as SimulationEvent];const score={...timeline[timeline.length-1].score};return {seed,finalScore:score,missionSuccess:evaluateMissionResult(mission,score,timeline),timeline,userGoals:score.home-mission.context.score.home,opponentGoals:score.away-mission.context.score.away,followsActualBaseline:true}}
export function runSingleSimulation(input:SimulationInput,seed:number):SingleSimulationResult{const mission=getMission(input.missionId),random=createSeededRandom(seed);let minute=mission.context.minute,score={...mission.context.score},index=0;const timeline:SimulationEvent[]=[];let endMinute=mission.objective.targetMinute;const baseDuration=Math.max(1,mission.objective.targetMinute-mission.context.minute)
  if(tacticalChangeScore(input)<=5)return actualFlowResult(input,seed)
  if(mission.type==='penalty_order'){const effects=input.expectedEffects;const orderBonus=(effects.chanceCreation+effects.attack+effects.staminaCost*.35-effects.counterRisk*.25)/2600;const successChance=Math.max(.35,Math.min(.78,.52+orderBonus+(input.instructions.riskLevel==='aggressive'?.04:0)));const userScores=random.chance(successChance);const opponentMisses=random.chance(.42+(effects.defensiveStability-50)/700);if(userScores)score.home+=1;if(!opponentMisses)score.away+=1;timeline.push({id:'penalty-order-120',minute:120,period:'EXTRA_TIME_SECOND_HALF',teamId:input.teamId,type:userScores?'goal':'shot',text:userScores?'키커 순서 변경이 적중합니다. 압박에 강한 키커가 성공합니다.':'바꾼 순서에서도 킥이 골키퍼에게 읽힙니다.',score:{...score},momentumDelta:userScores?12:-10,probability:successChance,isKeyEvent:true});if(opponentMisses)timeline.push({id:'penalty-order-121',minute:121,period:'EXTRA_TIME_SECOND_HALF',teamId:input.opponentTeamId,type:'save',text:'상대 키커의 슈팅을 골키퍼가 막아냅니다.',score:{...score},momentumDelta:14,probability:.42,isKeyEvent:true});const missionSuccess=evaluateMissionResult(mission,score,timeline);return {seed,finalScore:score,missionSuccess,timeline,userGoals:score.home-mission.context.score.home,opponentGoals:score.away-mission.context.score.away,followsActualBaseline:false}}
  while(minute<endMinute){minute=Math.min(endMinute,minute+random.integer(1,3));const progress=Math.min(1.8,(minute-mission.context.minute)/baseDuration);const pressDrain=input.instructions.pressingIntensity==='high'?.22:input.instructions.pressingIntensity==='low'?.08:.14;const tempoDrain=input.instructions.tempo==='fast'?.1:input.instructions.tempo==='slow'?-.02:.04;const staminaFactor=Math.max(.58,1-progress*(pressDrain+tempoDrain));const event=generateSimulationEvent({minute,endMinute,period:periodFor(minute),score,input,userMetrics:calculateTeamMetrics(input,staminaFactor),opponentMetrics:calculateOpponentMetrics(input,Math.max(.65,1-progress*.16)),random,eventIndex:index++});score=event.score;timeline.push(event);if(shouldEnterExtraTime(mission,minute,endMinute,score)){endMinute=120;timeline.push({id:`extra-time-kickoff-${index++}`,minute:91,period:'EXTRA_TIME_FIRST_HALF',teamId:input.teamId,type:'build_up',text:'90분 동안 승부를 가리지 못해 연장전에 돌입합니다.',score:{...score},momentumDelta:0,probability:1,isKeyEvent:true})}}
  const missionSuccess=evaluateMissionResult(mission,score,timeline);return {seed,finalScore:score,missionSuccess,timeline,userGoals:score.home-mission.context.score.home,opponentGoals:score.away-mission.context.score.away,followsActualBaseline:false}}
