import type { ActualMatchTimelineEvent, MatchPeriod, Mission, MissionType } from '../../entities/mission/types'
import type { Player, PlayerPosition, PlayerRole } from '../../entities/player/types'
import type { Team } from '../../entities/team/types'
import type { NormalizedWorldCupMatch, RawWorldCupData, WorldCupSnapshot, WorldCupStanding } from './WorldCupDataProvider'

type RecordValue=Record<string,any>
const obj=(value:unknown):RecordValue=>value&&typeof value==='object'?value as RecordValue:{}
const arr=(value:unknown):unknown[]=>Array.isArray(value)?value:[]
const num=(value:unknown,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback
const text=(value:unknown,fallback='')=>typeof value==='string'?value:fallback
const clamp=(value:number)=>Math.max(35,Math.min(92,Math.round(value)))
const teamId=(id:unknown)=>`api-football-team-${id}`
const playerId=(id:unknown)=>`api-football-player-${id}`

export function mapApiFootballToSnapshot(raw:RawWorldCupData):WorldCupSnapshot{const players=mapPlayers(raw.players),teams=mapTeams(raw.teams,players,raw.players),matches=raw.matches.map(mapMatch).filter((match):match is NormalizedWorldCupMatch=>Boolean(match)),standings=mapStandings(raw.standings),missions=raw.matches.flatMap((fixture,index)=>mapFixtureToMission(fixture,index));return {schemaVersion:1,generatedAt:raw.fetchedAt,provider:'api-football',league:raw.league,season:raw.season,missions,teams,players,matches,standings}}

export function mapPlayers(records:unknown[]):Player[]{return records.map(item=>{const root=obj(item),apiPlayer=obj(root.player),stats=obj(arr(root.statistics)[0]),games=obj(stats.games),goals=obj(stats.goals),passes=obj(stats.passes),tackles=obj(stats.tackles),dribbles=obj(stats.dribbles),position=mapPosition(text(games.position,'Midfielder')),rating=num(games.rating,6.7);if(!apiPlayer.id)return null;const boost=(rating-6)*8;return {id:playerId(apiPlayer.id),source:{provider:'api-football' as const,externalId:String(apiPlayer.id)},name:text(apiPlayer.name,`Player ${apiPlayer.id}`),shirtNumber:num(games.number,0),primaryPosition:position,positions:[{position,rating:88}],roles:[{role:defaultRole(position),rating:82}],attributes:{pace:clamp(66+boost+num(dribbles.success)*.15),finishing:clamp(58+boost+num(goals.total)*2),passing:clamp(64+boost+num(passes.key)*.6),crossing:clamp(60+boost+num(passes.key)*.4),dribbling:clamp(64+boost+num(dribbles.success)*.35),pressing:clamp(65+boost+num(tackles.interceptions)*.4),defense:clamp(58+boost+num(tackles.total)*.35),stamina:clamp(70+num(games.minutes)/300),offBall:clamp(63+boost+num(goals.assists)*1.5),heightPower:clamp(65+(parseHeight(apiPlayer.height)-178)*.7)}} as Player}).filter((player):player is Player=>Boolean(player))}

export function mapTeams(records:unknown[],players:Player[],rawPlayers:unknown[]=[]):Team[]{const byExternalTeam=new Map<string,Player[]>(),byExternalPlayer=new Map(players.map(player=>[player.source.externalId,player]));rawPlayers.forEach(record=>{const root=obj(record),externalTeamId=obj(arr(root.statistics)[0]).team?.id,player=byExternalPlayer.get(String(obj(root.player).id));if(!externalTeamId||!player)return;const roster=byExternalTeam.get(String(externalTeamId))??[];roster.push(player);byExternalTeam.set(String(externalTeamId),roster)})
  return records.map(item=>{const apiTeam=obj(obj(item).team);if(!apiTeam.id)return null;const roster=byExternalTeam.get(String(apiTeam.id))??[];return {id:teamId(apiTeam.id),source:{provider:'api-football' as const,externalId:String(apiTeam.id)},name:text(apiTeam.name,`Team ${apiTeam.id}`),shortName:text(apiTeam.code,text(apiTeam.name,'TEAM').slice(0,3).toUpperCase()),countryCode:text(apiTeam.code,'INT'),primaryColor:'#22c55e',secondaryColor:'#18181b',startingPlayerIds:roster.slice(0,11).map(p=>p.id),benchPlayerIds:roster.slice(11,20).map(p=>p.id)} as Team}).filter((team):team is Team=>Boolean(team))}

export function mapStandings(records:unknown[]):WorldCupStanding[]{return records.flatMap(item=>arr(obj(obj(item).league).standings).flatMap(group=>arr(group))).map(item=>{const row=obj(item),team=obj(row.team),all=obj(row.all),goals=obj(row.goals);return {rank:num(row.rank),teamId:teamId(team.id),group:text(row.group),played:num(all.played),won:num(all.win),drawn:num(all.draw),lost:num(all.lose),goalsFor:num(goals.for),goalsAgainst:num(goals.against),points:num(row.points)}})}

function mapMatch(item:unknown):NormalizedWorldCupMatch|null{const root=obj(item),fixture=obj(root.fixture),league=obj(root.league),teams=obj(root.teams),home=obj(teams.home),away=obj(teams.away),events=mapTimeline(root.events,fixture.id,home.id);if(!fixture.id||!home.id||!away.id)return null;return {id:`api-football-match-${fixture.id}`,date:text(fixture.date),stage:text(league.round,'World Cup 2026'),homeTeamId:teamId(home.id),awayTeamId:teamId(away.id),context:{matchId:`api-football-match-${fixture.id}`,competition:text(league.name,'FIFA World Cup'),season:String(league.season??2026),stage:text(league.round),period:'SECOND_HALF',minute:num(obj(fixture.status).elapsed,90),score:{home:num(obj(root.goals).home),away:num(obj(root.goals).away)},userTeamId:teamId(home.id),opponentTeamId:teamId(away.id),availableSubstitutions:5},timeline:events}}

function mapFixtureToMission(item:unknown,index:number):Mission[]{const root=obj(item),fixture=obj(root.fixture),teams=obj(root.teams),home=obj(teams.home),away=obj(teams.away),events=arr(root.events).map(obj);if(!fixture.id||!home.id||!away.id||events.length===0)return[];const scenario=detectScenario(events,root);if(!scenario)return[];const startScore=scoreAt(events,scenario.minute,home.id),timeline=mapTimeline(events.filter(event=>num(event.time?.elapsed)>scenario.minute),fixture.id,home.id,startScore);const dismissed=events.find(event=>text(event.type)==='Card'&&text(event.detail).toLowerCase().includes('red')&&num(event.time?.elapsed)<=scenario.minute&&event.team?.id===home.id);return [{id:`api-football-mission-${fixture.id}-${scenario.type}-${index}`,source:{provider:'api-football',matchExternalId:String(fixture.id)},title:scenario.title,type:scenario.type,difficulty:scenario.difficulty,situation:scenario.situation,objective:{type:scenario.type,title:scenario.objective,description:scenario.description,targetMinute:scenario.targetMinute,minimumGoalsFor:scenario.minimumGoalsFor,maximumGoalsAgainst:scenario.maximumGoalsAgainst},context:{matchId:`api-football-match-${fixture.id}`,competition:text(obj(root.league).name,'FIFA World Cup'),season:String(obj(root.league).season??2026),stage:text(obj(root.league).round),period:periodFor(scenario.minute),minute:scenario.minute,score:startScore,userTeamId:teamId(home.id),opponentTeamId:teamId(away.id),availableSubstitutions:5,dismissedPlayerId:dismissed?.player?.id?playerId(dismissed.player.id):undefined,dismissedPosition:dismissed?'CB':undefined},recommendedFormationId:scenario.type==='protect_lead'||scenario.type==='red_card_survival'?'formation-4231':scenario.type==='late_winner'||scenario.type==='extra_time_winner'?'formation-343':'formation-433',opponentTraits:['실제 경기 이벤트를 기반으로 한 상대 흐름','2026 월드컵 fixture snapshot에서 정규화'],teamProblems:scenario.type==='red_card_survival'?['수적 열세로 인한 수비 간격 문제']:['제한된 남은 시간과 체력 관리'],actualFlowSummary:`${scenario.minute}분 이후 실제 기록에서는 ${num(obj(root.goals).home)}-${num(obj(root.goals).away)}로 경기가 진행됐습니다.`,actualTimeline:timeline}]}

function detectScenario(events:RecordValue[],root:RecordValue){const homeId=root.teams?.home?.id,red=events.find(event=>event.team?.id===homeId&&text(event.type)==='Card'&&text(event.detail).toLowerCase().includes('red')&&num(event.time?.elapsed)<=60);if(red){const minute=num(red.time?.elapsed);return scenario('red_card_survival',minute,'10명으로 버텨라',`${minute}분, 수비수 퇴장`,`${Math.min(90,minute+25)}분까지 무실점`,Math.min(90,minute+25),4,undefined,0)}const status=text(root.fixture?.status?.short);const at90=scoreAt(events,90,homeId);if(['AET','PEN'].includes(status)&&at90.home===at90.away)return scenario('extra_time_winner',90,'연장전 승부수','연장 전반 시작, 동점','승부차기 전에 득점',120,5,1);const at70=scoreAt(events,70,homeId);if(at70.away-at70.home===1)return scenario('trailing_draw',70,'패배를 막아라','후반 70분, 한 골 열세','최소 무승부 만들기',90,3,1);const at75=scoreAt(events,75,homeId);if(at75.home-at75.away===1)return scenario('protect_lead',75,'리드를 지켜라','후반 75분, 한 골 리드','실점 없이 경기 종료',90,3,undefined,0);const at80=scoreAt(events,80,homeId);if(at80.home===at80.away)return scenario('late_winner',80,'마지막 10분','후반 80분, 동점','10분 안에 결승골 만들기',90,4,1);return null}
function scenario(type:MissionType,minute:number,title:string,situation:string,objective:string,targetMinute:number,difficulty:1|2|3|4|5,minimumGoalsFor?:number,maximumGoalsAgainst?:number){return {type,minute,title,situation,objective,description:objective,targetMinute,difficulty,minimumGoalsFor,maximumGoalsAgainst}}
function scoreAt(events:RecordValue[],minute:number,homeTeamId:unknown){let home=0,away=0;for(const event of events){if(num(event.time?.elapsed)>minute||text(event.type)!=='Goal')continue;if(event.team?.id===homeTeamId)home++;else away++}return {home,away}}
function mapTimeline(eventsValue:unknown,fixtureId:unknown,homeTeamId:unknown,initial={home:0,away:0}):ActualMatchTimelineEvent[]{let home=initial.home,away=initial.away;return arr(eventsValue).map((item,index)=>{const event=obj(item),minute=num(event.time?.elapsed);if(text(event.type)==='Goal'){if(event.team?.id===homeTeamId)home++;else away++}return {id:`api-football-event-${fixtureId}-${index}`,minute,period:periodFor(minute),teamId:teamId(event.team?.id??'unknown'),type:mapEventType(event),summary:`${text(event.team?.name,'팀')} · ${text(event.detail,text(event.type,'경기 이벤트'))}`,homeScore:home,awayScore:away,sourceEventId:event.player?.id?String(event.player.id):undefined}})}
function mapEventType(event:RecordValue):ActualMatchTimelineEvent['type']{const type=text(event.type).toLowerCase(),detail=text(event.detail).toLowerCase();if(type==='goal')return'goal';if(type.includes('card')&&detail.includes('red'))return'red_card';if(type.includes('subst'))return'substitution';return type.includes('shot')?'shot':'tactical_shift'}
function periodFor(minute:number):MatchPeriod{return minute<=45?'FIRST_HALF':minute<=90?'SECOND_HALF':minute<=105?'EXTRA_TIME_FIRST_HALF':'EXTRA_TIME_SECOND_HALF'}
function parseHeight(value:unknown){const match=text(value).match(/\d+/);return match?num(match[0],178):178}
function mapPosition(position:string):PlayerPosition{const p=position.toLowerCase();if(p.includes('goal'))return'GK';if(p.includes('def'))return'CB';if(p.includes('attack'))return'ST';return'CM'}
function defaultRole(position:PlayerPosition):PlayerRole{return position==='GK'?'goalkeeper':position==='CB'?'stopper':position==='ST'?'pressing_forward':'box_to_box'}
